philo1: 
	@gcc -g -pthread philo1.c -o philo && ./philo

philo2: 
	@gcc -g -pthread philo2.c -o philo && ./philo

philo3: 
	@gcc -g -pthread philo3.c -o philo && ./philo

philo4: 
	@gcc -g -pthread philo4.c -o philo && ./philo

philo5: 
	@gcc -g -pthread philo5.c -o philo && ./philo

philo6: 
	@gcc -g -pthread philo6.c -o philo && ./philo

philo7: 
	@gcc -g -pthread philo7.c -o philo && ./philo

philo8: 
	@gcc -g -pthread philo8.c -o philo && ./philo

philo9: 
	@gcc -g -pthread philo9.c -o philo && ./philo

philo10: 
	@gcc -g -pthread philo10.c -o philo && ./philo

philo11: 
	@gcc -g -pthread philo11.c -o philo && ./philo

philo12: 
	@gcc -g -pthread philo12.c -o philo && ./philo

philo13: 
	@gcc -g -pthread philo13.c -o philo && ./philo

philo15: 
	@gcc -g -pthread philo15.c -o philo && ./philo
