FROM debian:oldstable

RUN apt-get update && apt-get install -y nginx openssl

WORKDIR /ssl
RUN openssl \
    req -x509 \
    -nodes \
    -subj "/CN=localhost}" \
    -addext "subjectAltName=DNS:localhost" \
    -days 365 \
    -newkey rsa:2048 -keyout self-signed.key \
    -out self-signed.crt

RUN cp self-signed.crt /etc/ssl/certs/
RUN cp self-signed.key /etc/ssl/private/

COPY ./nginx.conf /etc/nginx/conf.d

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]