version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/conf.d/
      - ./public:/var/www/public/
      - /home/${USER}/42-Projects/inception/srcs/requirements/tools:/etc/nginx/ssl/
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    container_name: simple_nginx_html