version: '3'

services:
  nginx:
    build: 
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    restart: always
    networks:
      - inception

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - mysql_vol:/var/lib/mysql

volumes:
  mysql_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/dadoming/data/mysql
      o: bind
    name: mysql_vol
  
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/dadoming/data/wordpress
      o: bind
    name: wordpress_vol


networks:
  inception:
    driver: bridge
